# -*- coding: utf-8 -*-
"""hatexplain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lHvWbVIiooYe9CtFHl1GCiTxrh69227
"""

# Core ML
!pip install -q transformers datasets peft accelerate scikit-learn lime

# Gemini API
!pip install -q google-genai

"""installing dependencies"""

import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from datasets import load_dataset, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
    confusion_matrix
)

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback
)

from peft import (
    LoraConfig,
    get_peft_model,
    TaskType
)

from lime.lime_text import LimeTextExplainer

from google import genai

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)

"""it works on the colab gpu, cuda"""

!git clone https://github.com/hate-alert/HateXplain.git

!ls HateXplain/Data

import json
import pandas as pd

with open("HateXplain/Data/dataset.json", "r") as f:
    dataset = json.load(f)

with open("HateXplain/Data/post_id_divisions.json", "r") as f:
    splits = json.load(f)

print("Loaded dataset:", len(dataset))

def process_split(split_name):
    rows = []

    for post_id in splits[split_name]:
        item = dataset[post_id]

        text = " ".join(item["post_tokens"])

        labels = [ann["label"] for ann in item["annotators"]]

        majority_label = max(set(labels), key=labels.count)

        # Binary classification
        # normal -> 0
        # offensive / hatespeech -> 1
        label = 0 if majority_label == "normal" else 1

        rows.append({
            "comment_text": text,
            "label": label
        })

    return pd.DataFrame(rows)

train_df = process_split("train")
val_df = process_split("val")
test_df = process_split("test")

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

print(train_df["label"].value_counts())

"""imported hatexplain dataset from the git and converted the json file to dataframe"""

import matplotlib.pyplot as plt

plt.hist(train_df["label"], bins=2)
plt.xlabel("Class")
plt.ylabel("Count")
plt.title("Bias vs Neutral Distribution")
plt.show()

print(train_df["label"].value_counts(normalize=True))

"""implementing distilbert tokenizer and embedding"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_NAME = "bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
    problem_type="single_label_classification"
)

model.to(device)

print("BERT model loaded successfully")

"""now, applying loRa for faster and effecient training"""

!pip install --upgrade torchao

from peft import LoraConfig, get_peft_model, TaskType

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=16,
    lora_alpha=32,
    lora_dropout=0.1,
    bias="none",
    target_modules=["query", "key", "value"]
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)
test_dataset = Dataset.from_pandas(test_df)

train_dataset = train_dataset.rename_column("label", "labels")
val_dataset = val_dataset.rename_column("label", "labels")
test_dataset = test_dataset.rename_column("label", "labels")

print(train_dataset)

"""now we have proper labeling to the data

now we transform normal text to distilbert inputs
"""

def tokenize_function(example):
    return tokenizer(
        example["comment_text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

"""we will be tokenizing all the datasets we have"""

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

print("Tokenization complete!")

"""in the next cell, we have a metrics function, which makes the training more strong, after every epoch training, we get the scores(f1, recall, precision) so that there are no continuous range of imbalance outputs"""

import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    # Convert raw logits to predicted class
    preds = np.argmax(logits, axis=-1)

    # Binary classification metrics
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="binary"
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

"""next cell is concerned with the training, ive kept the learning rate moderate with perfect batch size, epoch is 4 as distilbert is already pretrained, dataset is also only ~15k"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",

    learning_rate=3e-5,
    weight_decay=0.01,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    num_train_epochs=6,

    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,

    logging_dir="./logs",
    logging_steps=100,

    fp16=True,

    report_to="none"
)

"""next cell treates the training engine, hooks distilbert and lora"""

import torch
import torch.nn as nn
from transformers import Trainer, EarlyStoppingCallback

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")

        outputs = model(**inputs)
        logits = outputs.get("logits")

        class_weights = torch.tensor(
            [1.0, 1.45],
            device=logits.device
        )

        loss_fn = nn.CrossEntropyLoss(weight=class_weights)

        loss = loss_fn(logits, labels)

        return (loss, outputs) if return_outputs else loss


trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics,
    callbacks=[
        EarlyStoppingCallback(early_stopping_patience=2)
    ]
)

trainer.train()

test_results = trainer.evaluate(test_dataset)

print(test_results)

from sklearn.metrics import classification_report
import numpy as np

predictions = trainer.predict(test_dataset)

preds = np.argmax(predictions.predictions, axis=-1)
labels = predictions.label_ids

print(classification_report(
    labels,
    preds,
    target_names=["Neutral", "Biased"]
))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(labels, preds)

print(cm)

"""lets save the model now"""

model.save_pretrained("./bias_model")
tokenizer.save_pretrained("./bias_model")

print("Model saved successfully")

"""now lime needs a prediction fn, we will initialize this"""

import torch
import torch.nn.functional as F
import numpy as np

def predict_proba(texts):
    model.eval()

    inputs = tokenizer(
        texts,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)
        probs = F.softmax(outputs.logits, dim=1)

    return probs.cpu().numpy()

"""lets initialize lime now"""

from lime.lime_text import LimeTextExplainer

explainer = LimeTextExplainer(
    class_names=["Neutral", "Biased"]
)

print("LIME initialized")

"""next block has explnable function"""

def explain_text(text):
    explanation = explainer.explain_instance(
        text,
        predict_proba,
        num_features=10
    )

    return explanation.as_list()

!pip install -q google-genai==1.21.1

from google import genai

from google import genai
import json

GEMINI_API_KEY = "AIzaSyBF5N7NklWp-Cm5ekUWskvfYCqzMFsLNWU"

client = genai.Client(api_key=GEMINI_API_KEY)

print("Gemini client initialized")

import time
import json

def gemini_semantic_analysis(text):
    prompt = f"""
You are an advanced AI bias detection engine.

Analyze the following text for semantic bias.

TEXT:
{text}

Return ONLY valid JSON.

Schema:
{{
  "loaded_language": number between 0 and 100,
  "identity_bias": number between 0 and 100,
  "emotional_framing": number between 0 and 100,
  "toxicity_risk": number between 0 and 100,
  "bias_type": "OVERGENERALIZATION or IDENTITY_BIAS or LOADED_LANGUAGE or EMOTIONAL_FRAMING or TOXICITY or NEUTRAL",
  "model_interpretation": "professional explanation",
  "neutral_rewrite": "neutral rewritten version"
}}
"""

    models = [
        "gemini-2.5-flash",
        "gemini-2.0-flash"
    ]

    for model_name in models:
        for attempt in range(3):
            try:
                response = client.models.generate_content(
                    model=model_name,
                    contents=prompt
                )

                raw = response.text.strip()

                if raw.startswith("```"):
                    raw = raw.replace("```json", "").replace("```", "").strip()

                return json.loads(raw)

            except Exception as e:
                print(f"Retry {attempt+1} failed on {model_name}: {e}")
                time.sleep(2)

    # fallback safe response
    return {
        "loaded_language": 50,
        "identity_bias": 0,
        "emotional_framing": 50,
        "toxicity_risk": 20,
        "bias_type": "NEUTRAL",
        "model_interpretation": "Semantic analysis temporarily unavailable.",
        "neutral_rewrite": text
    }

def build_attention_heatmap(text, lime_explanation):
    try:
        words = [str(word) for word, _ in lime_explanation]

        prompt = f"""
Analyze these words in context.

TEXT:
{text}

WORDS:
{words}

Return ONLY JSON list:
[
  {{
    "word": "example",
    "label": "highly_biased"
  }}
]
"""

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt
        )

        raw = response.text.strip()

        if raw.startswith("```"):
            raw = raw.replace("```json", "").replace("```", "").strip()

        labels = json.loads(raw)

        score_map = {
            str(word): float(score)
            for word, score in lime_explanation
        }

        return [
            {
                "word": item["word"],
                "score": round(score_map.get(item["word"], 0.0), 3),
                "label": item["label"]
            }
            for item in labels
        ]

    except:
        return [
            {
                "word": str(word),
                "score": round(float(score), 3),
                "label": "suspicious" if score > 0.03 else "neutral"
            }
            for word, score in lime_explanation
        ]

def analyze_text(text):
    prediction = predict_proba([text])[0]

    biased_score = float(prediction[1]) * 100

    lime_explanation = explain_text(text)
    heatmap = build_attention_heatmap(text, lime_explanation)
    semantic_data = gemini_semantic_analysis(text)

    semantic_average = (
        semantic_data["loaded_language"] +
        semantic_data["identity_bias"] +
        semantic_data["emotional_framing"] +
        semantic_data["toxicity_risk"]
    ) / 4

    # smarter fusion
    overall_score = max(
        biased_score,
        semantic_average
    )

    # semantic override
    if semantic_data["bias_type"] != "NEUTRAL":
        overall_score += 10

    overall_score = min(100, round(overall_score))

    if overall_score >= 70:
        risk = "HIGH"
    elif overall_score >= 40:
        risk = "MEDIUM"
    else:
        risk = "LOW"

    return {
        "bias_detected": overall_score >= 50,
        "overall_score": overall_score,
        "risk_level": risk,

        "semantic_vectors": {
            "loaded_language": semantic_data["loaded_language"],
            "identity_bias": semantic_data["identity_bias"],
            "emotional_framing": semantic_data["emotional_framing"],
            "toxicity_risk": semantic_data["toxicity_risk"]
        },

        "model_interpretation": semantic_data["model_interpretation"],

        "attention_heatmap": heatmap,

        "sentence_vector": {
            "sentence": text,
            "bias_type": semantic_data["bias_type"]
        },

        "neutral_rewrite": semantic_data["neutral_rewrite"]
    }

def get_risk_level(score):
    if score >= 80:
        return "HIGH"

    elif score >= 50:
        return "MEDIUM"

    return "LOW"

"""next, we want the format to be easy for frontend na"""



sample = "The media always manipulates public perception in favor of one ideology."

result = analyze_text(sample)

import json
print(json.dumps(result, indent=2))